services:
  database:
    image: postgres:17
    hostname: database
    container_name: database
    ports:
      - 15432:5432
    environment:
      POSTGRES_USER: newsletter
      POSTGRES_PASSWORD: welcome
      POSTGRES_DB: newsletter
    command: postgres -c "max_connections=1000"
