application:
  host: 127.0.0.1
  port: 8080
database:
  host: 127.0.0.1
  port: 15432
  username: newsletter
  password: welcome
  database: newsletter
email_client:
  host: 127.0.0.1
  sender: test@gmail.com
  token: SECRET_TOKEN
  timeout: 3s
