application:
  host: 127.0.0.1
  port: 8080
subscriber:
  database:
    connection:
      host: 127.0.0.1
      port: 15432
      username: newsletter
      password: welcome
      database: newsletter
    pool:
      min_connections: 5
      max_connections: 5
      acquire_timeout: 5s
  email:
    server:
      url: http://127.0.0.1
      token: SECRET_TOKEN
    client:
      sender: test@gmail.com
      timeout: 3s
